version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["yarn", "start:server"]
    volumes:
      - ./src:/usr/src/app  # Mount the app source code for development
    environment:
      DB_HOST: venture-test_test-db-vendure
      DB_PORT: 5432
      DB_NAME: venture-test
      DB_USERNAME: postgres
      DB_PASSWORD: 11e5a5880d9469b7e8ee
      VENDURE_PORT: 3000
      NODE_ENV: production

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:worker"]
    volumes:
      - ./src:/usr/src/app  # Mount the app source code for development
    depends_on:
      - server
    environment:
      DB_HOST: venture-test_test-db-vendure
      DB_PORT: 5432
      DB_NAME: venture-test
      DB_USERNAME: postgres
      DB_PASSWORD: 11e5a5880d9469b7e8ee
      NODE_ENV: production

volumes:
  vendure-data:
